### ISSUE TITLE
Specifying a data file with the "--file" argument causes a duplicate key exception

### ISSUE THREAD

**Issue by aschuhardt** [ttu/dotnet-fake-json-server#22]
Steps to reproduce:

1. Clone the repo
2. `cd` into the `dotnet-fake-json-server/FakeServer` directory
3. Create a file called "test.json"
4. Run the application with the following command: `dotnet run --file "test.json"`

I received the following trace after dotnet crashed:
```
PS C:\Users\aschuhardt\dotnet-fake-json-server\FakeServer> dotnet run --file "test.json"
Using launch settings from C:\Users\aschuhardt\dotnet-fake-json-server\FakeServer\Properties\launchSettings.json...
File: test.json

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: file
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at FakeServer.Program.Main(String[] args) in C:\Users\aschuhardt\dotnet-fake-json-server\FakeServer\Program.cs:line 38
```

Cause:

[This line adds a key "file" regardless of whether one has been added as a result of the command-line argument](https://github.com/aschuhardt/dotnet-fake-json-server/blob/master/FakeServer/Program.cs#L38)

**Comment by ttu** [comment]
Closed with https://github.com/ttu/dotnet-fake-json-server/commit/84ef889ac98025f539d04f3768217e84109840a4
